version: "3"

# titles are names of the containers after initialisation (check with docker ps [-a] whether they are running)
# docker comands: start, stop, run, build, pull, push, rm, rmi, images, ps, inspect, cp
# ports (-p) <external-port>:<internal-port> (mapping of ports)
# volumes (-v) <volume-on-host>:<volume-in-container> (mounts volume-on-host to container)
# docker-compose up -d for making containers detached (other commands: docker-compose run, stop, down (--volumes)
# Other options (in .yml): links (link to <name-other-container>:<variable-name-in-other-container> or if equal only on tag) (--link)
services:
        php:
                # build: ./docker-php
                image: php:7.4-fpm
                ports: 
                  - "5000:80"

        mysql:
                # build: ./docker-mysql
                image: mysql
                ports:
                  - "3306:3306"
                volumes:
                  - ./data:/var/lib/mysql


        nginx:
                build: ./docker-nginx
                ports: 
                  - "8000:80"
                volumes: 
                  # original file volume on nginx: /usr/share/nginx/html but in here altered in config files
                  - ./php-files:/var/www/include
                  # Done in Dockerfile:
                  #  - ./docker-nginx/nginx.conf:/etc/nginx
                  #  - ./docker-nginx/default.conf:/etc/nginx/conf.d
